"""empty message

Revision ID: ad452d777dad
Revises: 
Create Date: 2024-04-14 19:24:15.540282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad452d777dad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jurisdiction', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('upvotes', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['title'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('upvotes')
        batch_op.drop_column('jurisdiction')

    # ### end Alembic commands ###
